version: '3.6'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.9.1'
    container_name: swat-zookeeper
    ports:
      - "2181:2181"
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: 1
    networks:
      - water-treatment-network
    
  kafka:
    image: 'bitnami/kafka:3.6'
    container_name: swat-kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOSTNAME: localhost
      ALLOW_PLAINTEXT_LISTENER: 1
      KAFKA_CREATE_TOPICS: water-treatment,water-treatment-preproc
    networks:
      - water-treatment-network

  cmak:
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:latest
    container_name: swat-cmak
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    networks:
      - water-treatment-network

  spark:
    image: docker.io/bitnami/spark:3.5
    container_name: swat-spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
    networks:
      - water-treatment-network
    volumes:
        - ./:/swat-change-detection


networks:
  water-treatment-network:
    driver: bridge  