{
 "title": "Máté Hekfusz - SWaT Dashboard",
 "time": { "from": "2019-07-20T04:30:00.000Z", "to": "2019-07-20T08:40:00.000Z" },
 "panels": [
  {
   "title": "LIT 301 (10-second aggregate means) - showing a contextual anomaly starting at 07:13",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"water-treatment\")\r\n    |> range(start: 2019-07-20T04:30:00Z, stop: 2019-07-20T08:40:00Z)\r\n    |> filter(fn: (r) => r._field == \"LIT 301\")\r\n    |> aggregateWindow(every: 10s, fn: mean)"
    }
   ]
  },
  {
   "title": "Ratio of normal and attack records",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "kafka_consumer",
     "query": "import \"experimental/array\"\r\n \r\n|> array.from(rows: [{_time: 2020-01-01T00:00:00Z, _value: \"foo\"},{_time: 2020-01-02T00:00:00Z, _value: \"bar\"}])",
     "select": [
      [
       { "params": [ "attack_label" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "attack_label::field", "operator": "=", "value": "attack" }
     ]
    },
    {
     "measurement": "kafka_consumer",
     "query": "import \"experimental/array\"\r\n \r\n|> array.from(rows: [{_time: 2020-01-01T00:00:00Z, _value: \"foo\"},{_time: 2020-01-02T00:00:00Z, _value: \"bar\"}])",
     "select": [
      [
       { "params": [ "attack_label" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "attack_label::field", "operator": "=", "value": "normal" }
     ]
    }
   ]
  },
  {
   "title": "FIT 401 and MV 501 - note how FIT 401 also changes when MV 501 is attacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"water-treatment\")\r\n    |> range(start: 2019-07-20T04:30:00Z, stop: 2019-07-20T08:40:00Z)\r\n    |> filter(fn: (r) => r._field == \"FIT 401\" or r._field == \"MV 501\")\r\n    |> aggregateWindow(every: 10s, fn: mean)"
    }
   ]
  },
  {
   "title": "Attack occurrences - note how they all occur in the last portion of the data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"water-treatment\")\r\n    |> range(start: 2019-07-20T04:30:00Z, stop: 2019-07-20T08:40:00Z)\r\n    |> filter(fn: (r) => r._field == \"attack_label\")\r\n    |> map(\r\n        fn: (r) => ({r with\r\n            _value: if r._value == \"attack\" then\r\n                1\r\n            else\r\n                0,\r\n        }),\r\n    )\r\n    |> aggregateWindow(every: 10s, fn: max)"
    }
   ]
  },
  {
   "title": "Heatmap of MV201 and P101 - because they always share the same values, they were attacked at the same time shortly after 07:30",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"water-treatment\")\r\n    |> range(start: 2019-07-20T00:00:00Z, stop: 2019-07-20T23:59:59Z)\r\n    |> filter(fn: (r) => r._field == \"P101 Status\" or r._field == \"MV201\")\r\n    |> aggregateWindow(every: 20s, fn: mean)"
    }
   ]
  }
 ]
}